### ISSUE TITLE
GeoJson页面问题

### ISSUE THREAD

**Issue by Znonymous29** [ZvonimirSun/iszy-tools#158]
### BUG
- 表格加载时，仅以第一个Feature的数据作为属性，会遗漏其他Feature的属性

###  Feature
- Popup对话框可以添加属性和值

### Refactor
- 直接采用map.fitBounds定位Feature边界

**Comment by ZvonimirSun** [comment]
自用小项目，居然有人来提Pr，感动

**Comment by Znonymous29** [comment]
哈哈 最近有些geojson编辑的需求 正好看到你开源的编辑器。对比geojson.io，有些地方还挺好用的，同时发现了一些问题顺手帮你PR一下

**Comment by ZvonimirSun** [comment]
啊哈，我一开始就是觉得geojson.io有点慢，然后就参考它自己写了个，自用是够了
